"""
Django settings for cryptosite project.

Generated by 'django-admin startproject' using Django 1.10.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import django

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'j771+&4aa3walrz-kns8d+#%6**xzai27m)gz7o4l0&@0(1^3f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['40ade5eb.ngrok.io']

ROOT_URLCONF = 'paypal.urls'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'paypal.standard.ipn'
    'paypal.standard',
    'paypal.pro',
]

DATABASES = {'default':
                 {'ENGINE': 'django.db.backends.sqlite3',
                  'NAME': 'test.db',
                  }}
PAYPAL_IDENTITY_TOKEN = ''
INSTALLED_APPS = [
                     'django.contrib.auth',
                     'django.contrib.contenttypes',
                     'paypal.pro',
                     'paypal.standard',
                     'paypal.standard.ipn',
                     'paypal.standard.pdt',
                 ] + (['south'] if django.VERSION < (1, 7) else [])
CACHES = {
             'default': {
                 'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
                 'TIMEOUT': 0,
                 'KEY_PREFIX': 'paypal_tests_',
             }
         }
MIDDLEWARE_CLASSES = []
DEBUG = True

STATIC_URL = '/static/'

PAYPAL_TEST = True
PAYPAL_WPP_USER = "sashpro-facilitator_api1.mail.ru"
PAYPAL_WPP_PASSWORD = "6CCHUJYHTFAHU4SG"
PAYPAL_WPP_SIGNATURE = "An5ns1Kso7MWUdW4ErQKJJJ4qi4-ADPMmYaB3wNKmQovusZaIqITbV2a"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]