"""
Django settings for cryptosite project.

Generated by 'django-admin startproject' using Django 1.10.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'j771+&4aa3walrz-kns8d+#%6**xzai27m)gz7o4l0&@0(1^3f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

ROOT_URLCONF = 'paypal.urls'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'paypal.standard',
    'paypal.pro',
]


STATIC_URL = '/static/'

PAYPAL_TEST = True
PAYPAL_WPP_USER = "sashpro-facilitator_api1.mail.ru"
PAYPAL_WPP_PASSWORD = "6CCHUJYHTFAHU4SG"
PAYPAL_WPP_SIGNATURE = "An5ns1Kso7MWUdW4ErQKJJJ4qi4-ADPMmYaB3wNKmQovusZaIqITbV2a"
